alertmanager:
  persistentVolume:
    enabled: true
    storageClass: "gp2"
    size: 10Gi  # Adjust size if necessary

server:
  persistentVolume:
    enabled: true
    storageClass: "gp2"
    size: 10Gi  # Adjust size if necessary
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"
  service:
    type: NodePort
    nodePort: 30090

kubeStateMetrics:
  resources:
    requests:
      memory: "200Mi"
      cpu: "100m"
    limits:
      memory: "400Mi"
      cpu: "200m"

serverFiles:
  prometheus.yml:
    rule_files:
      - /etc/config/alerting-rules.yaml

groups:
- name: ResourceAlerts
  rules:
  - alert: HighCPUUsage
    expr: sum(rate(container_cpu_usage_seconds_total{namespace="your-namespace", container!="POD", container!=""}[5m])) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace="your-namespace"}) by (pod) < 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is underutilizing CPU"
      description: "CPU usage is less than 10% of requested resources for the last 5 minutes."
  - alert: HighMemoryUsage
    expr: sum(container_memory_usage_bytes{namespace="your-namespace", container!="POD", container!=""}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace="your-namespace"}) by (pod) < 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is underutilizing memory"
      description: "Memory usage is less than 10% of requested resources for the last 5 minutes."

